"""Generate sample TMDB-format movie dataset and train the model"""
import pandas as pd
import numpy as np
import json
from pathlib import Path

# Sample movies data
movies = [
    {"id":1,"title":"The Shawshank Redemption","overview":"Two imprisoned men bond over a number of years finding solace and eventual redemption through acts of common decency.","genres":"Drama","keywords":"prison,hope,freedom,redemption,friendship","vote_average":8.7,"vote_count":25000,"popularity":80,"release_date":"1994-09-23","status":"Released","imdb_id":"tt0111161","poster_path":"/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg","tagline":"Fear can hold you prisoner. Hope can set you free.","production_companies":"Castle Rock Entertainment","production_countries":"United States of America"},
    {"id":2,"title":"The Godfather","overview":"The aging patriarch of an organized crime dynasty transfers control to his reluctant son.","genres":"Drama,Crime","keywords":"mafia,family,crime,power,loyalty","vote_average":8.7,"vote_count":19000,"popularity":85,"release_date":"1972-03-14","status":"Released","imdb_id":"tt0068646","poster_path":"/3bhkrj58Vtu7enYsRolD1fZdja1.jpg","tagline":"An offer you can't refuse.","production_companies":"Paramount Pictures","production_countries":"United States of America"},
    {"id":3,"title":"The Dark Knight","overview":"Batman raises the stakes in his war on crime with the help of allies to dismantle the remaining criminal organizations.","genres":"Action,Crime,Drama,Thriller","keywords":"superhero,joker,batman,gotham,vigilante","vote_average":8.5,"vote_count":31000,"popularity":90,"release_date":"2008-07-16","status":"Released","imdb_id":"tt0468569","poster_path":"/qJ2tW6WMUDux911BTUgMe0Jt.jpg","tagline":"Why so serious?","production_companies":"Warner Bros Pictures","production_countries":"United States of America"},
    {"id":4,"title":"Pulp Fiction","overview":"The lives of two mob hitmen a boxer a gangster and his wife intertwine in four tales of violence and redemption.","genres":"Crime,Thriller","keywords":"nonlinear,crime,hitman,redemption,dark comedy","vote_average":8.5,"vote_count":26000,"popularity":75,"release_date":"1994-09-10","status":"Released","imdb_id":"tt0110912","poster_path":"/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg","tagline":"You won't know the facts until you've seen the fiction.","production_companies":"Miramax","production_countries":"United States of America"},
    {"id":5,"title":"Forrest Gump","overview":"The presidencies of Kennedy and Johnson the Vietnam War and other events unfold from the perspective of an Alabama man.","genres":"Drama,Comedy,Romance","keywords":"vietnam,destiny,running,love,history","vote_average":8.5,"vote_count":26000,"popularity":78,"release_date":"1994-06-23","status":"Released","imdb_id":"tt0109830","poster_path":"/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg","tagline":"Life is like a box of chocolates.","production_companies":"Paramount Pictures","production_countries":"United States of America"},
    {"id":6,"title":"Inception","overview":"A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.","genres":"Action,Science Fiction,Adventure","keywords":"dreams,subconscious,heist,mind,reality","vote_average":8.4,"vote_count":35000,"popularity":95,"release_date":"2010-07-15","status":"Released","imdb_id":"tt1375666","poster_path":"/9gk7adHYeDvHkCSEhnivolV3LGrP.jpg","tagline":"Your mind is the scene of the crime.","production_companies":"Warner Bros Pictures","production_countries":"United States of America"},
    {"id":7,"title":"Fight Club","overview":"An insomniac office worker and a devil-may-care soap maker form an underground fight club.","genres":"Drama,Thriller","keywords":"identity,rebellion,consumerism,chaos,underground","vote_average":8.4,"vote_count":27000,"popularity":73,"release_date":"1999-10-15","status":"Released","imdb_id":"tt0137523","poster_path":"/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg","tagline":"Mischief. Mayhem. Soap.","production_companies":"20th Century Fox","production_countries":"United States of America"},
    {"id":8,"title":"The Matrix","overview":"A computer hacker learns about the true nature of his reality and his role in the war against its controllers.","genres":"Action,Science Fiction","keywords":"artificial intelligence,matrix,simulation,hacker,chosen one","vote_average":8.2,"vote_count":24000,"popularity":80,"release_date":"1999-03-30","status":"Released","imdb_id":"tt0133093","poster_path":"/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg","tagline":"Welcome to the Real World.","production_companies":"Warner Bros Pictures","production_countries":"United States of America"},
    {"id":9,"title":"Goodfellas","overview":"The story of Henry Hill and his life in the mob covering his relationship with his wife Karen Hill.","genres":"Drama,Crime","keywords":"mafia,gangster,crime,mob,true story","vote_average":8.5,"vote_count":12000,"popularity":60,"release_date":"1990-09-12","status":"Released","imdb_id":"tt0099685","poster_path":"/aKuFiU82s5ISJDx1LDECQpT4hxe.jpg","tagline":"Three decades of life in the mafia.","production_companies":"Warner Bros Pictures","production_countries":"United States of America"},
    {"id":10,"title":"Interstellar","overview":"A team of explorers travel through a wormhole in space in an attempt to ensure humanity survival.","genres":"Adventure,Drama,Science Fiction","keywords":"space,wormhole,time,survival,exploration","vote_average":8.4,"vote_count":33000,"popularity":92,"release_date":"2014-11-05","status":"Released","imdb_id":"tt0816692","poster_path":"/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg","tagline":"Mankind was born on Earth. It was never meant to die here.","production_companies":"Paramount Pictures","production_countries":"United States of America"},
    {"id":11,"title":"The Lord of the Rings: The Return of the King","overview":"Gandalf and Aragorn lead the World of Men against Saurons army to draw his gaze from Frodo.","genres":"Adventure,Fantasy,Action","keywords":"middle earth,ring,epic,quest,battle","vote_average":8.5,"vote_count":23000,"popularity":75,"release_date":"2003-12-01","status":"Released","imdb_id":"tt0167260","poster_path":"/rCzpDGLbOoPwLjy7CStCoh0g.jpg","tagline":"The eye of the enemy is moving.","production_companies":"New Line Cinema","production_countries":"New Zealand"},
    {"id":12,"title":"Schindlers List","overview":"In German-occupied Poland industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.","genres":"Drama,History,War","keywords":"holocaust,jews,world war ii,rescue,humanity","vote_average":8.6,"vote_count":15000,"popularity":55,"release_date":"1993-12-15","status":"Released","imdb_id":"tt0108052","poster_path":"/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg","tagline":"The list is life.","production_companies":"Universal Pictures","production_countries":"United States of America"},
    {"id":13,"title":"Titanic","overview":"A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious ill-fated RMS Titanic.","genres":"Drama,Romance","keywords":"titanic,ship,love,disaster,ocean","vote_average":7.9,"vote_count":24000,"popularity":82,"release_date":"1997-11-18","status":"Released","imdb_id":"tt0120338","poster_path":"/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg","tagline":"Nothing on Earth could come between them.","production_companies":"Paramount Pictures","production_countries":"United States of America"},
    {"id":14,"title":"The Avengers","overview":"Earths mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.","genres":"Action,Adventure,Science Fiction","keywords":"superhero,avengers,alien,team,marvel","vote_average":7.7,"vote_count":30000,"popularity":95,"release_date":"2012-04-25","status":"Released","imdb_id":"tt0848228","poster_path":"/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg","tagline":"Some assembly required.","production_companies":"Marvel Studios","production_countries":"United States of America"},
    {"id":15,"title":"Jurassic Park","overview":"A pragmatic paleontologist touring an almost complete theme park is tasked with protecting children.","genres":"Adventure,Science Fiction,Thriller","keywords":"dinosaur,theme park,genetics,island,survival","vote_average":7.9,"vote_count":16000,"popularity":72,"release_date":"1993-06-11","status":"Released","imdb_id":"tt0107290","poster_path":"/oU7Oez2kVBft78T2urIGlLRn6gB.jpg","tagline":"An adventure 65 million years in the making.","production_companies":"Universal Pictures","production_countries":"United States of America"},
    {"id":16,"title":"Avatar","overview":"A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following orders.","genres":"Action,Adventure,Fantasy,Science Fiction","keywords":"alien,avatar,planet,nature,war","vote_average":7.6,"vote_count":30000,"popularity":90,"release_date":"2009-12-15","status":"Released","imdb_id":"tt0499549","poster_path":"/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg","tagline":"Enter the World.","production_companies":"20th Century Fox","production_countries":"United States of America"},
    {"id":17,"title":"Gladiator","overview":"A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.","genres":"Action,Adventure,Drama","keywords":"roman,gladiator,revenge,emperor,arena","vote_average":8.2,"vote_count":17000,"popularity":70,"release_date":"2000-05-01","status":"Released","imdb_id":"tt0172495","poster_path":"/ty8TGRuvJLPUmAR1H1nRIsgwIF.jpg","tagline":"Are you not entertained?","production_companies":"DreamWorks Pictures","production_countries":"United States of America"},
    {"id":18,"title":"The Lion King","overview":"Lion prince Simba and his father are targeted by his bitter uncle who wants to ascend the throne.","genres":"Animation,Family,Drama","keywords":"lion,africa,prince,kingdom,coming of age","vote_average":8.3,"vote_count":17000,"popularity":76,"release_date":"1994-06-24","status":"Released","imdb_id":"tt0110357","poster_path":"/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg","tagline":"Life's greatest adventure is finding your place.","production_companies":"Walt Disney Pictures","production_countries":"United States of America"},
    {"id":19,"title":"The Silence of the Lambs","overview":"A young FBI cadet must receive the help of an incarcerated manipulative cannibal killer.","genres":"Crime,Drama,Thriller,Horror","keywords":"serial killer,fbi,cannibal,psychological,suspense","vote_average":8.3,"vote_count":15000,"popularity":62,"release_date":"1991-02-01","status":"Released","imdb_id":"tt0102926","poster_path":"/rplLJ2hPcOQmkFhTqUte0MkEb9a.jpg","tagline":"To enter the mind of a killer she must challenge the mind of a madman.","production_companies":"Orion Pictures","production_countries":"United States of America"},
    {"id":20,"title":"Saving Private Ryan","overview":"Following the Normandy Landings a group of soldiers go behind enemy lines to retrieve a paratrooper.","genres":"Drama,History,War","keywords":"world war ii,normandy,soldiers,rescue,sacrifice","vote_average":8.2,"vote_count":15000,"popularity":65,"release_date":"1998-07-24","status":"Released","imdb_id":"tt0120815","poster_path":"/1wY4psJ5NVEhCuOYROwLH2XExM2.jpg","tagline":"The mission is a man.","production_companies":"DreamWorks Pictures","production_countries":"United States of America"},
    {"id":21,"title":"Star Wars","overview":"Luke Skywalker joins forces with a Jedi Knight to save the galaxy from the empires world destroying battle station.","genres":"Adventure,Action,Science Fiction","keywords":"space,jedi,force,empire,rebellion","vote_average":8.2,"vote_count":19000,"popularity":80,"release_date":"1977-05-25","status":"Released","imdb_id":"tt0076759","poster_path":"/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg","tagline":"A long time ago in a galaxy far far away.","production_companies":"Lucasfilm Ltd","production_countries":"United States of America"},
    {"id":22,"title":"The Departed","overview":"An undercover cop and a mole in the police attempt to identify each other while infiltrating a crime syndicate.","genres":"Drama,Thriller,Crime","keywords":"undercover,mole,police,crime,boston","vote_average":8.2,"vote_count":14000,"popularity":60,"release_date":"2006-10-05","status":"Released","imdb_id":"tt0407887","poster_path":"/nT97ifVT2J1yMQmeq20Hzd7Msv0.jpg","tagline":"Cops or criminals. When you're facing a loaded gun what's the difference?","production_companies":"Warner Bros Pictures","production_countries":"United States of America"},
    {"id":23,"title":"Whiplash","overview":"A promising young drummer enrolls at a music conservatory where his dreams of greatness are mentored by an instructor.","genres":"Drama,Music","keywords":"music,jazz,drums,obsession,mentor","vote_average":8.4,"vote_count":14000,"popularity":55,"release_date":"2014-10-10","status":"Released","imdb_id":"tt2582802","poster_path":"/7fn624j5lj3xTme2SgiLCeuedmO.jpg","tagline":"The road to greatness can take you to the edge.","production_companies":"Bold Films","production_countries":"United States of America"},
    {"id":24,"title":"The Prestige","overview":"Two stage magicians engage in competitive one-upmanship in an attempt to create the ultimate stage illusion.","genres":"Drama,Mystery,Thriller,Science Fiction","keywords":"magic,rivalry,obsession,illusion,sacrifice","vote_average":8.2,"vote_count":15000,"popularity":58,"release_date":"2006-10-19","status":"Released","imdb_id":"tt0482571","poster_path":"/tRNlZbgNCNOk0vMqEhNRYlLCgEH.jpg","tagline":"Are you watching closely?","production_companies":"Warner Bros Pictures","production_countries":"United States of America"},
    {"id":25,"title":"Django Unchained","overview":"With the help of a German bounty hunter a freed slave sets out to rescue his wife from a brutal plantation owner.","genres":"Drama,Western","keywords":"slavery,bounty hunter,revenge,western,freedom","vote_average":8.2,"vote_count":26000,"popularity":70,"release_date":"2012-12-25","status":"Released","imdb_id":"tt1853728","poster_path":"/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg","tagline":"Life liberty and the pursuit of vengeance.","production_companies":"Columbia Pictures","production_countries":"United States of America"},
    {"id":26,"title":"Joker","overview":"A mentally troubled comedian in Gotham City embarks on a downward spiral leading to the creation of an iconic villain.","genres":"Crime,Thriller,Drama","keywords":"joker,gotham,mental illness,villain,society","vote_average":8.2,"vote_count":24000,"popularity":85,"release_date":"2019-10-01","status":"Released","imdb_id":"tt7286456","poster_path":"/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg","tagline":"Put on a happy face.","production_companies":"Warner Bros Pictures","production_countries":"United States of America"},
    {"id":27,"title":"Parasite","overview":"Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.","genres":"Comedy,Thriller,Drama","keywords":"class,inequality,parasite,family,deception","vote_average":8.5,"vote_count":17000,"popularity":75,"release_date":"2019-05-30","status":"Released","imdb_id":"tt6751668","poster_path":"/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg","tagline":"Act like you own the place.","production_companies":"CJ Entertainment","production_countries":"South Korea"},
    {"id":28,"title":"Spider-Man: No Way Home","overview":"Spider-Man seeks help from Doctor Strange when his identity is revealed causing the multiverse to break open.","genres":"Action,Adventure,Science Fiction","keywords":"spider-man,multiverse,superhero,identity,marvel","vote_average":8.0,"vote_count":18000,"popularity":92,"release_date":"2021-12-15","status":"Released","imdb_id":"tt10872600","poster_path":"/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg","tagline":"The multiverse unleashed.","production_companies":"Marvel Studios","production_countries":"United States of America"},
    {"id":29,"title":"The Green Mile","overview":"The lives of guards on death row are affected by one of their charges a man accused of child murder who has a mysterious gift.","genres":"Fantasy,Drama,Crime","keywords":"prison,death row,gift,miracle,guard","vote_average":8.5,"vote_count":16000,"popularity":60,"release_date":"1999-12-10","status":"Released","imdb_id":"tt0120689","poster_path":"/velWPhVMQeQKcxggNEU8YmIo52R.jpg","tagline":"Miracles do happen.","production_companies":"Castle Rock Entertainment","production_countries":"United States of America"},
    {"id":30,"title":"Se7en","overview":"Two detectives hunt a serial killer who uses the seven deadly sins as his motives.","genres":"Crime,Mystery,Thriller","keywords":"serial killer,detective,seven deadly sins,dark,mystery","vote_average":8.3,"vote_count":14000,"popularity":62,"release_date":"1995-09-22","status":"Released","imdb_id":"tt0114369","poster_path":"/6yoghtyTpznpBik8EngEmJskVUO.jpg","tagline":"Seven deadly sins. Seven ways to die.","production_companies":"New Line Cinema","production_countries":"United States of America"},
    {"id":31,"title":"Iron Man","overview":"After being held captive in an Afghan cave billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.","genres":"Action,Science Fiction,Adventure","keywords":"iron man,superhero,armor,technology,marvel","vote_average":7.6,"vote_count":25000,"popularity":85,"release_date":"2008-04-30","status":"Released","imdb_id":"tt0371746","poster_path":"/78lPtwv72eTNqFW9COBYI0dWDJa.jpg","tagline":"Heroes aren't born. They're built.","production_companies":"Marvel Studios","production_countries":"United States of America"},
    {"id":32,"title":"The Terminator","overview":"A cyborg assassin is sent back in time to kill the mother of the future resistance leader.","genres":"Action,Thriller,Science Fiction","keywords":"cyborg,time travel,future,terminator,war","vote_average":7.6,"vote_count":12000,"popularity":65,"release_date":"1984-10-26","status":"Released","imdb_id":"tt0088247","poster_path":"/qvktm0BHcnmDisA2cG78YJ2HA2R.jpg","tagline":"Your future is in his hands.","production_companies":"Orion Pictures","production_countries":"United States of America"},
    {"id":33,"title":"Back to the Future","overview":"Marty McFly accidentally travels back in time and must ensure his parents meet and fall in love.","genres":"Adventure,Comedy,Science Fiction","keywords":"time travel,delorean,teenager,past,adventure","vote_average":8.3,"vote_count":18000,"popularity":72,"release_date":"1985-07-03","status":"Released","imdb_id":"tt0088763","poster_path":"/7lyBcpYB0Qt8gYhXYaXDfm3ZG3c.jpg","tagline":"He's the only kid ever to get into trouble before he was born.","production_companies":"Universal Pictures","production_countries":"United States of America"},
    {"id":34,"title":"Aliens","overview":"Ellen Ripley is rescued after drifting through space and returns to the moon where her crew encountered the hostile Alien.","genres":"Action,Thriller,Science Fiction,Horror","keywords":"alien,space,marines,survival,sequel","vote_average":7.9,"vote_count":11000,"popularity":60,"release_date":"1986-07-18","status":"Released","imdb_id":"tt0090605","poster_path":"/r1x5JGpyqkM2eYVqJ5msBppX7Zv.jpg","tagline":"This time it's war.","production_companies":"20th Century Fox","production_countries":"United States of America"},
    {"id":35,"title":"WALL-E","overview":"A robot left to clean up an abandoned Earth meets another robot and follows her into space.","genres":"Animation,Family,Science Fiction","keywords":"robot,earth,love,space,environment","vote_average":8.1,"vote_count":17000,"popularity":65,"release_date":"2008-06-22","status":"Released","imdb_id":"tt0910970","poster_path":"/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg","tagline":"After 700 years of doing what he was built for he'll discover what he was meant for.","production_companies":"Pixar","production_countries":"United States of America"},
    {"id":36,"title":"Coco","overview":"A boy who dreams of being a musician enters the Land of the Dead to find his great-great-grandfather.","genres":"Animation,Family,Fantasy,Music","keywords":"mexico,death,music,family,memory","vote_average":8.2,"vote_count":18000,"popularity":70,"release_date":"2017-10-27","status":"Released","imdb_id":"tt2380307","poster_path":"/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg","tagline":"The celebration of a lifetime.","production_companies":"Pixar","production_countries":"United States of America"},
    {"id":37,"title":"Mad Max: Fury Road","overview":"A woman rebels against a tyrannical ruler in postapocalyptic wasteland searching for her homeland.","genres":"Action,Adventure,Science Fiction,Thriller","keywords":"post-apocalyptic,desert,chase,survival,rebellion","vote_average":7.6,"vote_count":22000,"popularity":68,"release_date":"2015-05-13","status":"Released","imdb_id":"tt1392190","poster_path":"/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg","tagline":"What a lovely day.","production_companies":"Warner Bros Pictures","production_countries":"Australia"},
    {"id":38,"title":"The Truman Show","overview":"An insurance salesman discovers his whole life is actually a reality TV show.","genres":"Comedy,Drama","keywords":"reality tv,surveillance,freedom,truth,media","vote_average":8.1,"vote_count":16000,"popularity":60,"release_date":"1998-06-05","status":"Released","imdb_id":"tt0120382","poster_path":"/vuza0WqY239yBXOopRae2JWxCTp.jpg","tagline":"On the air. Unaware.","production_companies":"Paramount Pictures","production_countries":"United States of America"},
    {"id":39,"title":"Oppenheimer","overview":"The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.","genres":"Drama,History,Thriller","keywords":"atomic bomb,physics,war,scientist,manhattan project","vote_average":8.1,"vote_count":10000,"popularity":88,"release_date":"2023-07-19","status":"Released","imdb_id":"tt15398776","poster_path":"/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg","tagline":"The world forever changes.","production_companies":"Universal Pictures","production_countries":"United States of America"},
    {"id":40,"title":"Dune","overview":"Feature adaptation of Frank Herberts science fiction novel about the son of a noble family trying to avenge his fathers death.","genres":"Science Fiction,Adventure,Drama","keywords":"desert,spice,chosen one,politics,epic","vote_average":7.8,"vote_count":11000,"popularity":82,"release_date":"2021-09-15","status":"Released","imdb_id":"tt1160419","poster_path":"/d5NXSklXo0qyIYkgV94XAgMIckC.jpg","tagline":"It begins.","production_companies":"Legendary Pictures","production_countries":"United States of America"},
    {"id":41,"title":"The Social Network","overview":"As Harvard students create a social networking site the founders face personal and legal complications.","genres":"Drama","keywords":"facebook,technology,betrayal,startup,ambition","vote_average":7.3,"vote_count":13000,"popularity":55,"release_date":"2010-10-01","status":"Released","imdb_id":"tt1285016","poster_path":"/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg","tagline":"You don't get to 500 million friends without making a few enemies.","production_companies":"Columbia Pictures","production_countries":"United States of America"},
    {"id":42,"title":"Blade Runner 2049","overview":"Young Blade Runner K's discovery of a secret leads him on a quest to find Rick Deckard who has been missing.","genres":"Science Fiction,Drama,Mystery","keywords":"replicant,dystopia,future,identity,artificial intelligence","vote_average":7.5,"vote_count":12000,"popularity":60,"release_date":"2017-10-04","status":"Released","imdb_id":"tt1856101","poster_path":"/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg","tagline":"The key to the future is finally unearthed.","production_companies":"Warner Bros Pictures","production_countries":"United States of America"},
    {"id":43,"title":"Toy Story","overview":"A cowboy doll is profoundly threatened when a new spaceman figure supplants him as top toy in a boys room.","genres":"Animation,Comedy,Family","keywords":"toy,friendship,adventure,jealousy,imagination","vote_average":8.0,"vote_count":17000,"popularity":68,"release_date":"1995-10-30","status":"Released","imdb_id":"tt0114709","poster_path":"/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg","tagline":"The adventure takes off!","production_companies":"Pixar","production_countries":"United States of America"},
    {"id":44,"title":"No Country for Old Men","overview":"Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and finds two million dollars.","genres":"Crime,Drama,Thriller","keywords":"hitman,western,fate,violence,desert","vote_average":7.9,"vote_count":11000,"popularity":55,"release_date":"2007-06-13","status":"Released","imdb_id":"tt0477348","poster_path":"/bj1v6YSd1lE4gvmG8sPYMTcXBPT.jpg","tagline":"There are no clean getaways.","production_companies":"Miramax","production_countries":"United States of America"},
    {"id":45,"title":"John Wick","overview":"An ex-hitman comes out of retirement to track down the gangsters that killed his dog.","genres":"Action,Thriller","keywords":"hitman,revenge,dog,assassin,underworld","vote_average":7.4,"vote_count":16000,"popularity":72,"release_date":"2014-10-22","status":"Released","imdb_id":"tt2911666","poster_path":"/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg","tagline":"Don't set him off.","production_companies":"Lionsgate","production_countries":"United States of America"},
    {"id":46,"title":"Get Out","overview":"A young African-American visits his white girlfriends parents for the weekend where his uneasiness about their reception of him leads to a nightmarish discovery.","genres":"Horror,Mystery,Thriller","keywords":"racism,horror,hypnosis,suburban,social commentary","vote_average":7.6,"vote_count":13000,"popularity":58,"release_date":"2017-02-24","status":"Released","imdb_id":"tt5052448","poster_path":"/tFXcEccSQMf3zy7uCiqrmopQ3Zy.jpg","tagline":"Just because you're invited doesn't mean you're welcome.","production_companies":"Universal Pictures","production_countries":"United States of America"},
    {"id":47,"title":"Spirited Away","overview":"During her familys move to the suburbs a young girl wanders into a world ruled by gods witches and spirits.","genres":"Animation,Family,Fantasy","keywords":"spirit,japan,anime,magical,journey","vote_average":8.5,"vote_count":15000,"popularity":62,"release_date":"2001-07-20","status":"Released","imdb_id":"tt0245429","poster_path":"/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg","tagline":"","production_companies":"Studio Ghibli","production_countries":"Japan"},
    {"id":48,"title":"The Wolf of Wall Street","overview":"Based on the true story of Jordan Belfort from his rise to a wealthy stockbroker to his fall involving crime and corruption.","genres":"Crime,Drama,Comedy","keywords":"wall street,greed,stock market,corruption,wealth","vote_average":8.0,"vote_count":21000,"popularity":70,"release_date":"2013-12-25","status":"Released","imdb_id":"tt0993846","poster_path":"/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg","tagline":"","production_companies":"Paramount Pictures","production_countries":"United States of America"},
    {"id":49,"title":"Shutter Island","overview":"Two U.S. Marshals are sent to investigate the disappearance of a patient from a hospital for the criminally insane.","genres":"Drama,Thriller,Mystery","keywords":"island,psychiatric hospital,investigation,twist,conspiracy","vote_average":8.2,"vote_count":22000,"popularity":68,"release_date":"2010-02-14","status":"Released","imdb_id":"tt1130884","poster_path":"/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg","tagline":"Some places never let you go.","production_companies":"Paramount Pictures","production_countries":"United States of America"},
    {"id":50,"title":"Everything Everywhere All at Once","overview":"An aging Chinese immigrant is swept up in an insane adventure where she must connect with parallel universe versions of herself.","genres":"Action,Adventure,Comedy,Science Fiction","keywords":"multiverse,family,immigrant,martial arts,absurdist","vote_average":7.8,"vote_count":10000,"popularity":75,"release_date":"2022-03-24","status":"Released","imdb_id":"tt6710474","poster_path":"/w3LxiVFoqqKpGoKg536lFcrBESR.jpg","tagline":"The universe is so much bigger than you realize.","production_companies":"A24","production_countries":"United States of America"},
]

def format_json_col(value):
    if pd.isna(value) or value == '':
        return '[]'
    items = [v.strip() for v in str(value).split(',')]
    return str([{"name": i} for i in items])

print("Creating dataset...")
df = pd.DataFrame(movies)

# Format JSON columns as the training script expects
df['genres'] = df['genres'].apply(lambda x: format_json_col(x))
df['keywords'] = df['keywords'].apply(lambda x: format_json_col(x))
df['production_companies'] = df['production_companies'].apply(lambda x: format_json_col(x))
df['production_countries'] = df['production_countries'].apply(lambda x: format_json_col(x))

csv_path = Path('./TMDB  IMDB Movies Dataset.csv')
df.to_csv(csv_path, index=False)
print(f"Created dataset with {len(df)} movies at {csv_path}")

# Now train with relaxed settings for small dataset
print("\n--- Starting Training ---\n")

import sys
sys.path.insert(0, '.')

# Monkey-patch the trainer for small dataset
from train import MovieRecommenderTrainer

trainer = MovieRecommenderTrainer(
    output_dir='./models',
    use_dimensionality_reduction=False  # Not needed for small dataset
)

df_result, sim_matrix = trainer.train(
    str(csv_path),
    quality_threshold='low',  # Keep all movies (5+ votes)
    max_movies=None
)

print(f"\nFinal: {len(df_result)} movies, matrix: {sim_matrix.shape}")
print("Training complete! Model files saved to ./models/")
